# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
    - bioc-release
    - bioc-devel
sudo: false
cache: packages
compiler: clang

bioc_packages:
    - BiocFileCache
    - BiocParallel
    - SummarizedExperiment
    - SingleCellExperiment

apt_packages:
    - libhdf5-dev

after_success:
    - Rscript -e 'covr::codecov()'
