---
title: "CellBench User's Guide"
author: "Shian Su"
date: "`r Sys.Date()`"
output: BiocStyle::pdf_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Markdown

```{r, eval = FALSE}
library(CellBench)
library(purrr)

load_sc_data()

map <- purrr::map
partial <- purrr::partial

subset_data <- cellbench_sc_data %>%
    map(partial(keep_high_var_genes, n = 1000)) %>%
    map(partial(sample_cells, n = 50))

clustering_method <- list(
    sc3 = clustering_sc3,
    race_id = clustering_raceid
)

options("CellBench.threads" = 4)

res <- begin_benchmark(
    subset_data,
    clustering_method
)
```

# Benchmarking normalisation methods

```{r}
subset_data <- cellbench_sc_data %>%
    map(partial(keep_high_var_genes, n = 500)) %>%
    map(partial(sample_cells, n = 150))

no_norm <- function(sce) {
    log(counts(sce) + 1)
}

normalisation <- list(
    none = no_norm,
    lib_size = lib_size_norm_expr,
    scran = scran_norm_expr
)

res <- apply_methods(
    subset_data,
    normalisation
)

add_cell_line <- function(result, data) {
    tibble::add_column(result, cell_line = subset_data[[data]]$cell_line)
}

pipeline_summarise(res, drop.steps = FALSE) %>%
    dplyr::mutate(result = map(result, compute_pca)) %>%
    dplyr::mutate(result = map2(result, data, add_cell_line)) %>%
    tidyr::unnest() %>%
    ggplot(aes(x = PC1, y = PC2, col = cell_line)) +
    geom_point() +
    facet_grid(data~normalisation, switch = "y")

```

